version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: urlShortenerDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: